INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_categories.apps.AppCategoriesConfig',
    'app_products.apps.AppProductsConfig',
    'app_search.apps.AppSearchConfig',
    'app_users.apps.AppUsersConfig',
    'app_cart.apps.AppCartConfig',
    'app_order.apps.AppOrderConfig',
    'app_payment.apps.AppPaymentConfig',
    'debug_toolbar',
    'mptt',
]
